server:
  port: 8004 #服务端口
#spring相关配置
spring:
  application:
    name: cloud-provider-hystrix-payment
#    cloud-provider-hystrix-fusing-payment  #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #数据库驱动包
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ######
#mybatis:配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.zzd.springcloud.common.pojo    # 所有pojo别名类所在包

##eureka配置
#eureka:
#  client:
#    #表示是否将自己注册进eureka  默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机配置
#      defaultZone: http://localhost:7001/eureka
#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    #服务名称修改
    instance-id: cloud-provider-hystrix-payment
    #访问路径可以显示ip地址
    prefer-ip-address: true