server:
  port: 8200
spring:
  application:
    name: mcroservice-order  #服务名

##eureka配置
#eureka:
#  client:
#    #表示是否将自己注册进eureka  默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机配置
#      defaultZone: http://localhost:7001/eureka

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    #服务名称修改
    instance-id: order8200
    #访问路径可以显示ip地址
    prefer-ip-address: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间，设置等待5000为5秒时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口  TODO:日志的功能没有实现
    com.zzd.springcloud.provider.service.PaymentService: debug