server:
  port: 8100
spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率值介于0到1之间，1表示全部采集
        probability: 1
  application:
    name: mcroservice-order  #服务名

##eureka配置
#eureka:
#  client:
#    #表示是否将自己注册进eureka  默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机配置
#      defaultZone: http://localhost:7001/eureka

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    #服务名称修改
    instance-id: order8100
    #访问路径可以显示ip地址
    prefer-ip-address: true

